#!/bin/sh
zypper addrepo --refresh --name 'Main Update Repository' 'http://download.opensuse.org/update/leap/$releasever/oss/' 'repo-update';
zypper addrepo --refresh --name 'Update Repository (Non-Oss)' 'http://download.opensuse.org/update/leap/$releasever/non-oss/' 'repo-update-non-oss';
zypper addrepo --refresh --name 'Update repository of openSUSE Backports' 'http://download.opensuse.org/update/leap/$releasever/backports/' 'repo-backports-update';
zypper addrepo --disable --refresh --name 'Update repository of openSUSE Backports (Debug)' 'http://download.opensuse.org/update/leap/$releasever/backports_debug/' 'repo-backports-debug-update';
zypper addrepo --refresh --name 'Update repository with updates from SUSE Linux Enterprise 15' 'http://download.opensuse.org/update/leap/$releasever/sle/' 'repo-sle-update';
zypper addrepo --disable --refresh --name 'Update repository with updates from SUSE Linux Enterprise 15 (Debug)' 'http://download.opensuse.org/debug/update/leap/$releasever/sle/' 'repo-sle-debug-update';
zypper addrepo --refresh --name 'Main Repository' 'http://download.opensuse.org/distribution/leap/$releasever/repo/oss/' 'repo-oss';
zypper addrepo --refresh --name 'Non-OSS Repository' 'http://download.opensuse.org/distribution/leap/$releasever/repo/non-oss/' 'repo-non-oss';
zypper addrepo --disable --refresh --name 'Debug Repository' 'http://download.opensuse.org/debug/distribution/leap/$releasever/repo/oss/' 'repo-debug';
zypper addrepo --disable --refresh --name 'Update Repository (Debug)' 'http://download.opensuse.org/debug/update/leap/$releasever/oss/' 'repo-debug-update';
zypper addrepo --disable --refresh --name 'Debug Repository (Non-OSS)' 'http://download.opensuse.org/debug/distribution/leap/$releasever/repo/non-oss/' 'repo-debug-non-oss';
zypper addrepo --disable --refresh --name 'Update Repository (Debug, Non-OSS)' 'http://download.opensuse.org/debug/update/leap/$releasever/non-oss/' 'repo-debug-update-non-oss';
zypper addrepo --disable --refresh --name 'Source Repository' 'http://download.opensuse.org/source/distribution/leap/$releasever/repo/oss/' 'repo-source';
